title: TempPrep
description: Temp Preparation material for android
author: Me

# Theme settings
remote_theme: just-the-docs/just-the-docs

# Theme configuration
color_scheme: dark
search_enabled: true
search:
  heading_level: 2
  previews: 3

# UI settings
back_to_top: true
back_to_top_text: "Back to top"

# Aux links
aux_links:
  "GitHub Repository": "https://github.com/DeveloperDotLalit/temp-prep"

# Footer
footer_content: "Copyright &copy; 2024 DevNotes. All rights reserved."

# Permalinks
permalink: /:path/

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-relative-links

